/* Generated; CSV SHA256: 3b3b21cef4b2bd21f3ca6301673fa4ca2d8ed8359cf93036c9341a741ae7dc3e */
#include "iq_points.h"
const iq_point_def_t iq_points[IQ_POINT_COUNT] = {
    {0, 1, 5, IQ_GROUP_LIVE, 1, 0.1, 5, "VAB", "IQData-Voltage-AB", "Phase A-B RMS voltage; decoded physical meter reply; display comparison pending", "current_meter_sample"},
    {0, 2, 5, IQ_GROUP_LIVE, 1, 0.1, 5, "VBC", "IQData-Voltage-BC", "Phase B-C RMS voltage; decoded physical meter reply; display comparison pending", "current_meter_sample"},
    {0, 3, 5, IQ_GROUP_LIVE, 1, 0.1, 5, "VCA", "IQData-Voltage-CA", "Phase C-A RMS voltage; decoded physical meter reply; display comparison pending", "current_meter_sample"},
    {0, 4, 3, IQ_GROUP_LIVE, 1, 0.1, 5, "IA", "IQData-Current-A", "Phase A RMS current; decoded physical meter reply; display comparison pending", "current_meter_sample"},
    {0, 5, 3, IQ_GROUP_LIVE, 1, 0.1, 5, "IB", "IQData-Current-B", "Phase B RMS current; decoded physical meter reply; display comparison pending", "current_meter_sample"},
    {0, 6, 3, IQ_GROUP_LIVE, 1, 0.1, 5, "IC", "IQData-Current-C", "Phase C RMS current; decoded physical meter reply; display comparison pending", "current_meter_sample"},
    {0, 7, 5, IQ_GROUP_LIVE, 1, 0.1, 5, "VAN", "IQData-Voltage-AN", "Phase A-neutral RMS voltage; decoded physical meter reply; display comparison pending", "current_meter_sample"},
    {0, 8, 5, IQ_GROUP_LIVE, 1, 0.1, 5, "VBN", "IQData-Voltage-BN", "Phase B-neutral RMS voltage; decoded physical meter reply; display comparison pending", "current_meter_sample"},
    {0, 9, 5, IQ_GROUP_LIVE, 1, 0.1, 5, "VCN", "IQData-Voltage-CN", "Phase C-neutral RMS voltage; decoded physical meter reply; display comparison pending", "current_meter_sample"},
    {0, 10, 48, IQ_GROUP_LIVE, 0.001, 0.1, 5, "P_W", "IQData-Real-Power", "Meter real power; decoded physical meter reply; display comparison pending", "current_meter_sample"},
    {0, 11, 12, IQ_GROUP_LIVE, 0.001, 0.1, 5, "Q_var", "IQData-Reactive-Power", "Meter reactive power; positive W with negative var means inductive/lagging; decoded physical meter reply; display comparison pending", "current_meter_sample"},
    {0, 12, 15, IQ_GROUP_LIVE, 1, 0.01, 5, "PF", "IQData-Power-Factor", "Meter PF: negative=lagging, positive=leading; calculation mode unverified; decoded physical meter reply; display comparison pending", "current_meter_sample"},
    {0, 13, 27, IQ_GROUP_LIVE, 1, 0.1, 5, "FREQUENCY_Hz", "IQData-Frequency", "Meter frequency; decoded physical meter reply; display comparison pending", "current_meter_sample"},
    {0, 14, 48, IQ_GROUP_LIVE, 0.001, 0.1, 5, "DEMAND_W", "IQData-Demand", "Meter demand; decoded physical meter reply; display comparison pending", "current_meter_sample"},
    {0, 15, 19, IQ_GROUP_LIVE, 1, 0.1, 5, "ENERGY_kWh", "IQData-Energy", "Meter unsigned 24-bit energy counter; decoded physical meter reply; display comparison pending", "current_meter_sample"},
    {0, 16, 19, IQ_GROUP_LIVE, 0.001, 0.1, 5, "ENERGY_Wh", "IQData-Energy-Coarse", "Meter scaled energy buffer; lower precision than Energy; decoded physical meter reply; display comparison pending", "current_meter_sample"},
    {0, 17, 9, IQ_GROUP_LIVE, 0.001, 0.1, 5, "S_PQ_estimate_VA", "IQData-Apparent-Power-PQ-Estimate", "Estimate sqrt(P^2+Q^2); excludes separate distortion power; decoded physical meter reply; display comparison pending", "estimate_from_current_meter_sample"},
    {0, 18, 15, IQ_GROUP_LIVE, 1, 0.01, 5, "PF_PQ_magnitude", "IQData-Power-Factor-PQ-Estimate", "Estimate abs(P)/sqrt(P^2+Q^2); not a THD measurement; decoded physical meter reply; display comparison pending", "estimate_from_current_meter_sample"},
    {0, 20, 73, IQ_GROUP_LIVE_HEALTH, 1, 1, 0, "age_seconds", "IQData-Sample-Age", "Seconds since the last meter sample; fault if timestamp unavailable", "age_of_current_meter_sample"},
    {0, 100, 3, IQ_GROUP_TRIP, 1, 0.01, 180.0, "TRIP_IA", "IQData-Trip-Current-A", "Trip-buffer Current-A; event time and retention unknown; not a live measurement", "trip_buffer_read_time_not_event_time"},
    {0, 101, 3, IQ_GROUP_TRIP, 1, 0.01, 180.0, "TRIP_IB", "IQData-Trip-Current-B", "Trip-buffer Current-B; event time and retention unknown; not a live measurement", "trip_buffer_read_time_not_event_time"},
    {0, 102, 3, IQ_GROUP_TRIP, 1, 0.01, 180.0, "TRIP_IC", "IQData-Trip-Current-C", "Trip-buffer Current-C; event time and retention unknown; not a live measurement", "trip_buffer_read_time_not_event_time"},
    {0, 103, 5, IQ_GROUP_TRIP, 1, 0.01, 180.0, "TRIP_VAB", "IQData-Trip-Voltage-AB", "Trip-buffer Voltage-AB; event time and retention unknown; not a live measurement", "trip_buffer_read_time_not_event_time"},
    {0, 104, 5, IQ_GROUP_TRIP, 1, 0.01, 180.0, "TRIP_VBC", "IQData-Trip-Voltage-BC", "Trip-buffer Voltage-BC; event time and retention unknown; not a live measurement", "trip_buffer_read_time_not_event_time"},
    {0, 105, 5, IQ_GROUP_TRIP, 1, 0.01, 180.0, "TRIP_VCA", "IQData-Trip-Voltage-CA", "Trip-buffer Voltage-CA; event time and retention unknown; not a live measurement", "trip_buffer_read_time_not_event_time"},
    {0, 106, 5, IQ_GROUP_TRIP, 1, 0.01, 180.0, "TRIP_VAN", "IQData-Trip-Voltage-AN", "Trip-buffer Voltage-AN; event time and retention unknown; not a live measurement", "trip_buffer_read_time_not_event_time"},
    {0, 107, 5, IQ_GROUP_TRIP, 1, 0.01, 180.0, "TRIP_VBN", "IQData-Trip-Voltage-BN", "Trip-buffer Voltage-BN; event time and retention unknown; not a live measurement", "trip_buffer_read_time_not_event_time"},
    {0, 108, 5, IQ_GROUP_TRIP, 1, 0.01, 180.0, "TRIP_VCN", "IQData-Trip-Voltage-CN", "Trip-buffer Voltage-CN; event time and retention unknown; not a live measurement", "trip_buffer_read_time_not_event_time"},
    {0, 109, 47, IQ_GROUP_TRIP, 1, 0.01, 180.0, "TRIP_P_W", "IQData-Trip-Real-Power", "Trip-buffer Real-Power; event time and retention unknown; not a live measurement", "trip_buffer_read_time_not_event_time"},
    {0, 110, 47, IQ_GROUP_TRIP, 1, 0.01, 180.0, "TRIP_DEMAND_W", "IQData-Trip-Demand", "Trip-buffer Demand; event time and retention unknown; not a live measurement", "trip_buffer_read_time_not_event_time"},
    {0, 111, 18, IQ_GROUP_TRIP, 1, 0.01, 180.0, "TRIP_ENERGY_Wh", "IQData-Trip-Energy", "Trip-buffer Energy; event time and retention unknown; not a live measurement", "trip_buffer_read_time_not_event_time"},
    {0, 112, 27, IQ_GROUP_TRIP, 1, 0.01, 180.0, "TRIP_FREQUENCY_Hz", "IQData-Trip-Frequency", "Trip-buffer Frequency; event time and retention unknown; not a live measurement", "trip_buffer_read_time_not_event_time"},
    {0, 113, 11, IQ_GROUP_TRIP, 1, 0.01, 180.0, "TRIP_Q_var", "IQData-Trip-Reactive-Power", "Trip-buffer Reactive-Power; event time and retention unknown; not a live measurement", "trip_buffer_read_time_not_event_time"},
    {0, 114, 15, IQ_GROUP_TRIP, 1, 0.01, 180.0, "TRIP_PF", "IQData-Trip-Power-Factor", "Trip-buffer Power-Factor; event time and retention unknown; not a live measurement", "trip_buffer_read_time_not_event_time"},
    {0, 200, 95, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "FIRMWARE_REVISION", "IQData-Firmware-Revision", "Raw firmware byte from setpoints buffer; not communication protocol version", "configuration_read_time"},
    {0, 201, 95, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "FIRMWARE_VERSION", "IQData-Firmware-Version", "Raw firmware byte from setpoints buffer; not communication protocol version", "configuration_read_time"},
    {0, 202, 95, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "SW1_RAW", "IQData-SW1-Raw", "Raw SW1 byte; each bit value 1 means OFF and 0 means ON", "configuration_read_time"},
    {0, 203, 95, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "SW2_RAW", "IQData-SW2-Raw", "Raw SW2 byte; each bit value 1 means OFF and 0 means ON", "configuration_read_time"},
    {0, 204, 95, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "SW3_RAW", "IQData-SW3-Raw", "Raw SW3 byte; each bit value 1 means OFF and 0 means ON", "configuration_read_time"},
    {0, 205, 95, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "SW4_RAW", "IQData-SW4-Raw", "Raw SW4 byte; each bit value 1 means OFF and 0 means ON", "configuration_read_time"},
    {0, 206, 95, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "SW5_RAW", "IQData-SW5-Raw", "Raw SW5 byte; each bit value 1 means OFF and 0 means ON", "configuration_read_time"},
    {0, 207, 95, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "SW6_RAW", "IQData-SW6-Raw", "Raw SW6 byte; each bit value 1 means OFF and 0 means ON", "configuration_read_time"},
    {0, 210, 3, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "CONFIG_CT_PRIMARY_A", "IQData-Config-CT-Primary", "Configured CT primary rating; not a current measurement", "configuration_read_time"},
    {0, 211, 3, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "CONFIG_CT_SECONDARY_A", "IQData-Config-CT-Secondary", "Configured CT secondary rating, 5 A", "configuration_read_time"},
    {0, 212, 27, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "CONFIG_FREQUENCY_Hz", "IQData-Config-Line-Frequency", "Configured nominal line frequency", "configuration_read_time"},
    {0, 213, 95, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "CONFIG_WIRING_WIRES", "IQData-Config-Wiring-Wires", "Configured AC wiring: 3 or 4 wires", "configuration_read_time"},
    {0, 214, 95, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "CONFIG_PT_RATIO", "IQData-Config-PT-Ratio", "Configured PT primary-to-secondary voltage ratio", "configuration_read_time"},
    {0, 215, 72, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "CONFIG_DEMAND_MINUTES", "IQData-Config-Demand-Window", "Configured internal demand window; bypassed when external sync is enabled", "configuration_read_time"},
    {0, 216, 5, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "CONFIG_NOMINAL_LL_V", "IQData-Config-Nominal-Voltage-LL", "Configured nominal line-to-line voltage; international PT selection overrides SW4", "configuration_read_time"},
    {0, 217, 5, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "CONFIG_NOMINAL_LN_V", "IQData-Config-Nominal-Voltage-LN", "Configured nominal line-to-neutral voltage; international PT selection overrides SW4", "configuration_read_time"},
    {0, 218, 18, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "CONFIG_PULSE_Wh", "IQData-Config-Pulse-Energy", "Configured energy per output pulse; not an energy measurement", "configuration_read_time"},
    {0, 219, 98, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "CONFIG_OVERVOLTAGE_PERCENT", "IQData-Config-Overvoltage-Threshold", "Configured percent of nominal voltage for overvoltage detection", "configuration_read_time"},
    {0, 220, 98, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "CONFIG_UNDERVOLTAGE_PERCENT", "IQData-Config-Undervoltage-Threshold", "Configured percent of nominal voltage for undervoltage detection", "configuration_read_time"},
    {0, 221, 98, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "CONFIG_UNBALANCE_PERCENT", "IQData-Config-Unbalance-Threshold", "Configured phase unbalance detection percent", "configuration_read_time"},
    {0, 222, 73, IQ_GROUP_SETTINGS, 1, 0.01, 3600.0, "CONFIG_PROTECTION_DELAY_S", "IQData-Config-Protection-Delay", "Configured protective delay; used only when delayed action is enabled", "configuration_read_time"},
    {0, 300, 98, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "VLL_IMBALANCE_pct", "IQData-Voltage-Imbalance", "RMS line-voltage maximum absolute deviation from phase mean / mean; not sequence-component unbalance", "gateway_session_reset_on_restart"},
    {0, 301, 98, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "CURRENT_IMBALANCE_pct", "IQData-Current-Imbalance", "RMS phase-current maximum absolute deviation from phase mean / mean", "gateway_session_reset_on_restart"},
    {0, 302, 95, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "HIGHEST_CURRENT_PHASE", "IQData-Highest-Current-Phase", "Largest RMS current: A=1, B=2, C=3; ties choose lowest index; invalid with zero current", "gateway_session_reset_on_restart"},
    {0, 303, 3, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "HIGHEST_CURRENT_A", "IQData-Highest-Phase-Current", "Largest of the three RMS phase currents", "gateway_session_reset_on_restart"},
    {0, 304, 5, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "SESSION_VLL_MIN_V", "IQData-Session-Voltage-Minimum", "Minimum sampled RMS line voltage across phases since gateway restart", "gateway_session_reset_on_restart"},
    {0, 305, 5, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "SESSION_VLL_MAX_V", "IQData-Session-Voltage-Maximum", "Maximum sampled RMS line voltage across phases since gateway restart", "gateway_session_reset_on_restart"},
    {0, 306, 3, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "SESSION_CURRENT_MIN_A", "IQData-Session-Current-Minimum", "Minimum sampled phase RMS current since gateway restart", "gateway_session_reset_on_restart"},
    {0, 307, 3, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "SESSION_CURRENT_MAX_A", "IQData-Session-Current-Maximum", "Maximum sampled phase RMS current since gateway restart", "gateway_session_reset_on_restart"},
    {0, 308, 27, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "SESSION_FREQUENCY_MIN_Hz", "IQData-Session-Frequency-Minimum", "Minimum sampled meter frequency since gateway restart", "gateway_session_reset_on_restart"},
    {0, 309, 27, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "SESSION_FREQUENCY_MAX_Hz", "IQData-Session-Frequency-Maximum", "Maximum sampled meter frequency since gateway restart", "gateway_session_reset_on_restart"},
    {0, 310, 15, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "SESSION_PF_MIN", "IQData-Session-PF-Magnitude-Minimum", "Minimum absolute meter PF since gateway restart; not a distortion measurement", "gateway_session_reset_on_restart"},
    {0, 311, 15, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "SESSION_PF_MAX", "IQData-Session-PF-Magnitude-Maximum", "Maximum absolute meter PF since gateway restart", "gateway_session_reset_on_restart"},
    {0, 312, 48, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "SESSION_AVERAGE_POWER_kW", "IQData-Session-Average-Power", "Time-weighted net power over valid observed intervals only; trapezoidal interpolation", "gateway_session_reset_on_restart"},
    {0, 313, 48, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "SESSION_PEAK_POWER_kW", "IQData-Session-Peak-Power", "Maximum sampled signed real power since gateway restart", "gateway_session_reset_on_restart"},
    {0, 314, 48, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "LOAD_CHANGE_kW", "IQData-Load-Change", "Change from previous fresh real-power sample; invalid across gaps beyond configured maximum", "gateway_session_reset_on_restart"},
    {0, 315, 73, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "LOW_PF_CONTINUOUS_s", "IQData-Low-PF-Continuous-Duration", "Consecutive observed seconds with both endpoint PF magnitudes below configured threshold", "gateway_session_reset_on_restart"},
    {0, 316, 73, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "LOW_PF_TOTAL_s", "IQData-Session-Low-PF-Duration", "Accumulated observed intervals with both endpoint PF magnitudes below configured threshold", "gateway_session_reset_on_restart"},
    {0, 317, 73, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "FREQUENCY_EXCURSION_CONTINUOUS_s", "IQData-Frequency-Excursion-Duration", "Consecutive observed seconds outside configured nominal frequency tolerance", "gateway_session_reset_on_restart"},
    {0, 318, 73, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "FREQUENCY_EXCURSION_TOTAL_s", "IQData-Session-Frequency-Excursion-Duration", "Accumulated observed intervals with both endpoints outside configured frequency tolerance", "gateway_session_reset_on_restart"},
    {0, 319, 73, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "VOLTAGE_EXCURSION_CONTINUOUS_s", "IQData-Voltage-Excursion-Duration", "Consecutive observed seconds with any line voltage outside configured nominal tolerance; invalid without nominal voltage", "gateway_session_reset_on_restart"},
    {0, 320, 73, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "VOLTAGE_EXCURSION_TOTAL_s", "IQData-Session-Voltage-Excursion-Duration", "Accumulated observed intervals outside configured nominal voltage tolerance; invalid without nominal voltage", "gateway_session_reset_on_restart"},
    {0, 321, 48, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "ROLLING_15MIN_DEMAND_kW", "IQData-Rolling-15-Minute-Demand", "Time-weighted net power across a complete continuous 15-minute window; invalid during warmup or gaps", "gateway_session_reset_on_restart"},
    {0, 322, 98, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "ROLLING_15MIN_LOAD_FACTOR_pct", "IQData-Rolling-15-Minute-Load-Factor", "100 times 15-minute average / sampled peak; valid only for complete nonnegative-power window with positive peak", "gateway_session_reset_on_restart"},
    {0, 323, 71, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "SESSION_POWER_COVERAGE_h", "IQData-Session-Power-Coverage", "Sum of valid observed power intervals since gateway restart; excludes gaps", "gateway_session_reset_on_restart"},
    {0, 324, 73, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "ROLLING_POWER_COVERAGE_s", "IQData-Rolling-Power-Coverage", "Valid observed power seconds in the trailing 15 minutes; full value requires 900 seconds", "gateway_session_reset_on_restart"},
    {0, 325, 19, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "OBSERVED_ENERGY_kWh", "IQData-Observed-Session-Energy", "Sum of nondecreasing counter increments across valid adjacent observations only; 1 kWh resolution; excludes gaps and resets", "gateway_session_reset_on_restart"},
    {0, 326, 19, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "ROLLING_HOUR_ENERGY_kWh", "IQData-Rolling-Hour-Energy", "Counter change over a fully observed trailing hour; boundary interpolated; 1 kWh counter resolution", "gateway_session_reset_on_restart"},
    {0, 327, 19, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "ROLLING_DAY_ENERGY_kWh", "IQData-Rolling-Day-Energy", "Counter change over a fully observed trailing 24 hours; boundary interpolated; 1 kWh counter resolution", "gateway_session_reset_on_restart"},
    {0, 328, 71, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "CONTINUOUS_ENERGY_COVERAGE_h", "IQData-Continuous-Energy-Coverage", "Duration of current uninterrupted valid nondecreasing energy-counter sequence, retained up to 24 hours", "gateway_session_reset_on_restart"},
    {0, 329, 95, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "ACCEPTED_SAMPLES", "IQData-Diagnostics-Sample-Count", "Distinct fresh meter observations accepted since gateway restart", "gateway_session_reset_on_restart"},
    {0, 330, 73, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "DIAGNOSTICS_AGE_s", "IQData-Diagnostics-Session-Age", "Elapsed meter observation time since first accepted sample after gateway restart", "gateway_session_reset_on_restart"},
    {0, 331, 95, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "SAMPLE_GAP_COUNT", "IQData-Diagnostics-Sample-Gaps", "Observed intervals exceeding configured maximum gap; cumulative since gateway restart", "gateway_session_reset_on_restart"},
    {0, 332, 95, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "ENERGY_COUNTER_RESET_COUNT", "IQData-Energy-Counter-Decreases", "Observed energy counter decreases; reset and wrap are not distinguished", "gateway_session_reset_on_restart"},
    {0, 333, 95, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "OUT_OF_ORDER_COUNT", "IQData-Diagnostics-Out-of-Order-Count", "Rejected distinct observations older than last accepted timestamp", "gateway_session_reset_on_restart"},
    {0, 334, 73, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "EXCLUDED_GAP_TIME_s", "IQData-Diagnostics-Excluded-Gap-Time", "Total duration of excluded intervals exceeding maximum gap; not interpolated", "gateway_session_reset_on_restart"},
    {0, 335, 5, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "NOMINAL_VOLTAGE_V", "IQData-Diagnostics-Nominal-Voltage", "Configured nominal line voltage for excursion checks; invalid when not configured", "gateway_session_reset_on_restart"},
    {0, 336, 27, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "NOMINAL_FREQUENCY_Hz", "IQData-Diagnostics-Nominal-Frequency", "Configured nominal frequency for excursion checks", "gateway_session_reset_on_restart"},
    {0, 337, 15, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "LOW_PF_THRESHOLD", "IQData-Diagnostics-Low-PF-Threshold", "PF magnitude threshold for live diagnostic duration; not a meter alarm setting", "gateway_session_reset_on_restart"},
    {0, 338, 98, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "VOLTAGE_TOLERANCE_pct", "IQData-Diagnostics-Voltage-Tolerance", "Allowed percentage deviation from configured nominal line voltage", "gateway_session_reset_on_restart"},
    {0, 339, 27, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "FREQUENCY_TOLERANCE_Hz", "IQData-Diagnostics-Frequency-Tolerance", "Allowed absolute deviation from configured nominal frequency", "gateway_session_reset_on_restart"},
    {0, 340, 71, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "SESSION_ENERGY_COVERAGE_h", "IQData-Session-Energy-Coverage", "Sum of observed valid energy-counter intervals; excludes gaps and decreases", "gateway_session_reset_on_restart"},
    {0, 341, 73, IQ_GROUP_DERIVED, 1, 0.01, 5.0, "LATEST_SAMPLE_INTERVAL_s", "IQData-Diagnostics-Sample-Interval", "Time between latest two accepted snapshots; exposes skipped or delayed samples", "gateway_session_reset_on_restart"},
    {0, 400, 95, IQ_GROUP_HEALTH, 1, 0.01, 10, "POLL_ATTEMPTS", "IQData-Measurement-Poll-Count", "Recorder communication diagnostic: attempts; counters since poll_health state was created", "persistent_poll_health_state"},
    {0, 401, 95, IQ_GROUP_HEALTH, 1, 0.01, 10, "POLL_FAILURES", "IQData-Measurement-Poll-Failures", "Recorder communication diagnostic: failures; counters since poll_health state was created", "persistent_poll_health_state"},
    {0, 402, 98, IQ_GROUP_HEALTH, 1, 0.01, 10, "POLL_FAILURE_PERCENT", "IQData-Measurement-Poll-Failure-Rate", "Recorder communication diagnostic: failure_percent; counters since poll_health state was created", "persistent_poll_health_state"},
    {0, 403, 95, IQ_GROUP_HEALTH, 1, 0.01, 10, "POLL_MALFORMED", "IQData-Malformed-Meter-Writes", "Recorder communication diagnostic: malformed_writes; counters since poll_health state was created", "persistent_poll_health_state"},
    {0, 404, 73, IQ_GROUP_HEALTH, 1, 0.01, 10, "POLL_DURATION", "IQData-Measurement-Poll-Duration", "Recorder communication diagnostic: last_duration_seconds; counters since poll_health state was created", "persistent_poll_health_state"},
    {0, 405, 95, IQ_GROUP_HEALTH, 1, 0.01, 10, "DIAG_ATTEMPTS", "IQData-Diagnostic-Poll-Count", "Recorder communication diagnostic: attempts; counters since poll_health state was created", "persistent_poll_health_state"},
    {0, 406, 95, IQ_GROUP_HEALTH, 1, 0.01, 10, "DIAG_FAILURES", "IQData-Diagnostic-Poll-Failures", "Recorder communication diagnostic: failures; counters since poll_health state was created", "persistent_poll_health_state"},
    {0, 407, 95, IQ_GROUP_HEALTH, 1, 0.01, 10, "POLL_CONSECUTIVE_FAILURES", "IQData-Consecutive-Poll-Failures", "Recorder communication diagnostic: consecutive_failures; counters since poll_health state was created", "persistent_poll_health_state"},
    {0, 408, 95, IQ_GROUP_HEALTH, 1, 0.01, 10, "POLL_LAST_STOP", "IQData-Last-Poll-Stop-Code", "Recorder communication diagnostic: last_stop_code; counters since poll_health state was created", "persistent_poll_health_state"},
    {3, 1, 95, IQ_GROUP_LIVE_HEALTH, 1, 0, 5, "all_18_live_readings_good", "IQData-Telemetry-Healthy", "Active when all standard electrical readings are valid and no more than 5 seconds old; diagnostics carry individual quality", "current_live_group_quality"},
    {3, 2, 95, IQ_GROUP_LIVE_HEALTH, 1, 0, 0, "display_verified", "IQData-Display-Verified", "Active only after contemporaneous physical display comparison is recorded", "recorded_display_comparison"},
    {3, 10, 95, IQ_GROUP_FLAGS, 1, 0, 30.0, "FLAGS_TRIP", "IQData-Flags-Trip", "Current diagnostic buffer: Trip flag", "diagnostic_buffer_read_time"},
    {3, 11, 95, IQ_GROUP_FLAGS, 1, 0, 30.0, "FLAGS_ALARM", "IQData-Flags-Alarm", "Current diagnostic buffer: Alarm flag", "diagnostic_buffer_read_time"},
    {3, 12, 95, IQ_GROUP_FLAGS, 1, 0, 30.0, "FLAGS_EXTERNAL", "IQData-Flags-External", "Current diagnostic buffer: External cause", "diagnostic_buffer_read_time"},
    {3, 13, 95, IQ_GROUP_FLAGS, 1, 0, 30.0, "FLAGS_OVERVOLTAGE", "IQData-Flags-Overvoltage", "Current diagnostic buffer: Overvoltage cause", "diagnostic_buffer_read_time"},
    {3, 14, 95, IQ_GROUP_FLAGS, 1, 0, 30.0, "FLAGS_UNDERVOLTAGE", "IQData-Flags-Undervoltage", "Current diagnostic buffer: Undervoltage cause", "diagnostic_buffer_read_time"},
    {3, 15, 95, IQ_GROUP_FLAGS, 1, 0, 30.0, "FLAGS_PHASE_UNBALANCE", "IQData-Flags-Phase-Unbalance", "Current diagnostic buffer: Phase unbalance cause", "diagnostic_buffer_read_time"},
    {3, 16, 95, IQ_GROUP_FLAGS, 1, 0, 30.0, "FLAGS_PHASE_LOSS", "IQData-Flags-Phase-Loss", "Current diagnostic buffer: Phase loss cause", "diagnostic_buffer_read_time"},
    {3, 17, 95, IQ_GROUP_FLAGS, 1, 0, 30.0, "FLAGS_PHASE_REVERSAL", "IQData-Flags-Phase-Reversal", "Current diagnostic buffer: Phase reversal cause", "diagnostic_buffer_read_time"},
    {3, 18, 95, IQ_GROUP_FLAGS, 1, 0, 30.0, "FLAGS_RAM_ROM_FAILURE", "IQData-Flags-RAM-ROM-Failure", "Current diagnostic buffer: RAM or ROM failure cause", "diagnostic_buffer_read_time"},
    {3, 30, 95, IQ_GROUP_TRIP, 1, 0, 180.0, "TRIP_TRIP", "IQData-Trip-Trip", "Trip buffer; event time and retention are unknown: Trip flag", "trip_buffer_read_time_not_event_time"},
    {3, 31, 95, IQ_GROUP_TRIP, 1, 0, 180.0, "TRIP_ALARM", "IQData-Trip-Alarm", "Trip buffer; event time and retention are unknown: Alarm flag", "trip_buffer_read_time_not_event_time"},
    {3, 32, 95, IQ_GROUP_TRIP, 1, 0, 180.0, "TRIP_EXTERNAL", "IQData-Trip-External", "Trip buffer; event time and retention are unknown: External cause", "trip_buffer_read_time_not_event_time"},
    {3, 33, 95, IQ_GROUP_TRIP, 1, 0, 180.0, "TRIP_OVERVOLTAGE", "IQData-Trip-Overvoltage", "Trip buffer; event time and retention are unknown: Overvoltage cause", "trip_buffer_read_time_not_event_time"},
    {3, 34, 95, IQ_GROUP_TRIP, 1, 0, 180.0, "TRIP_UNDERVOLTAGE", "IQData-Trip-Undervoltage", "Trip buffer; event time and retention are unknown: Undervoltage cause", "trip_buffer_read_time_not_event_time"},
    {3, 35, 95, IQ_GROUP_TRIP, 1, 0, 180.0, "TRIP_PHASE_UNBALANCE", "IQData-Trip-Phase-Unbalance", "Trip buffer; event time and retention are unknown: Phase unbalance cause", "trip_buffer_read_time_not_event_time"},
    {3, 36, 95, IQ_GROUP_TRIP, 1, 0, 180.0, "TRIP_PHASE_LOSS", "IQData-Trip-Phase-Loss", "Trip buffer; event time and retention are unknown: Phase loss cause", "trip_buffer_read_time_not_event_time"},
    {3, 37, 95, IQ_GROUP_TRIP, 1, 0, 180.0, "TRIP_PHASE_REVERSAL", "IQData-Trip-Phase-Reversal", "Trip buffer; event time and retention are unknown: Phase reversal cause", "trip_buffer_read_time_not_event_time"},
    {3, 38, 95, IQ_GROUP_TRIP, 1, 0, 180.0, "TRIP_RAM_ROM_FAILURE", "IQData-Trip-RAM-ROM-Failure", "Trip buffer; event time and retention are unknown: RAM or ROM failure cause", "trip_buffer_read_time_not_event_time"},
    {3, 39, 95, IQ_GROUP_TRIP, 1, 0, 180.0, "TRIP_DATA_VALID", "IQData-Trip-Data-Valid", "Trip flag is set and all trip measurements have valid scale flags; event time unknown, never live data", "trip_buffer_read_time_not_event_time"},
    {3, 100, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW1_1_ON", "IQData-SW1-1-ON", "SW1 switch1 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 101, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW1_2_ON", "IQData-SW1-2-ON", "SW1 switch2 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 102, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW1_3_ON", "IQData-SW1-3-ON", "SW1 switch3 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 103, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW1_4_ON", "IQData-SW1-4-ON", "SW1 switch4 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 104, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW1_5_ON", "IQData-SW1-5-ON", "SW1 switch5 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 105, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW1_6_ON", "IQData-SW1-6-ON", "SW1 switch6 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 106, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW1_7_ON", "IQData-SW1-7-ON", "SW1 switch7 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 107, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW1_8_ON", "IQData-SW1-8-ON", "SW1 switch8 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 108, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW2_1_ON", "IQData-SW2-1-ON", "SW2 switch1 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 109, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW2_2_ON", "IQData-SW2-2-ON", "SW2 switch2 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 110, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW2_3_ON", "IQData-SW2-3-ON", "SW2 switch3 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 111, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW2_4_ON", "IQData-SW2-4-ON", "SW2 switch4 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 112, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW2_5_ON", "IQData-SW2-5-ON", "SW2 switch5 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 113, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW2_6_ON", "IQData-SW2-6-ON", "SW2 switch6 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 114, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW2_7_ON", "IQData-SW2-7-ON", "SW2 switch7 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 115, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW2_8_ON", "IQData-SW2-8-ON", "SW2 switch8 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 116, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW3_1_ON", "IQData-SW3-1-ON", "SW3 switch1 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 117, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW3_2_ON", "IQData-SW3-2-ON", "SW3 switch2 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 118, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW3_3_ON", "IQData-SW3-3-ON", "SW3 switch3 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 119, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW3_4_ON", "IQData-SW3-4-ON", "SW3 switch4 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 120, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW3_5_ON", "IQData-SW3-5-ON", "SW3 switch5 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 121, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW3_6_ON", "IQData-SW3-6-ON", "SW3 switch6 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 122, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW3_7_ON", "IQData-SW3-7-ON", "SW3 switch7 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 123, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW3_8_ON", "IQData-SW3-8-ON", "SW3 switch8 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 124, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW4_1_ON", "IQData-SW4-1-ON", "SW4 switch1 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 125, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW4_2_ON", "IQData-SW4-2-ON", "SW4 switch2 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 126, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW4_3_ON", "IQData-SW4-3-ON", "SW4 switch3 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 127, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW4_4_ON", "IQData-SW4-4-ON", "SW4 switch4 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 128, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW4_5_ON", "IQData-SW4-5-ON", "SW4 switch5 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 129, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW4_6_ON", "IQData-SW4-6-ON", "SW4 switch6 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 130, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW4_7_ON", "IQData-SW4-7-ON", "SW4 switch7 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 131, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW4_8_ON", "IQData-SW4-8-ON", "SW4 switch8 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 132, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW5_1_ON", "IQData-SW5-1-ON", "SW5 switch1 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 133, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW5_2_ON", "IQData-SW5-2-ON", "SW5 switch2 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 134, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW5_3_ON", "IQData-SW5-3-ON", "SW5 switch3 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 135, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW5_4_ON", "IQData-SW5-4-ON", "SW5 switch4 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 136, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW5_5_ON", "IQData-SW5-5-ON", "SW5 switch5 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 137, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW5_6_ON", "IQData-SW5-6-ON", "SW5 switch6 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 138, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW5_7_ON", "IQData-SW5-7-ON", "SW5 switch7 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 139, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW5_8_ON", "IQData-SW5-8-ON", "SW5 switch8 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 140, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW6_1_ON", "IQData-SW6-1-ON", "SW6 switch1 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 141, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW6_2_ON", "IQData-SW6-2-ON", "SW6 switch2 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 142, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW6_3_ON", "IQData-SW6-3-ON", "SW6 switch3 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 143, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW6_4_ON", "IQData-SW6-4-ON", "SW6 switch4 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 144, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW6_5_ON", "IQData-SW6-5-ON", "SW6 switch5 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 145, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW6_6_ON", "IQData-SW6-6-ON", "SW6 switch6 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 146, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW6_7_ON", "IQData-SW6-7-ON", "SW6 switch7 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 147, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "SW6_8_ON", "IQData-SW6-8-ON", "SW6 switch8 is ON; reports configuration, does not change it", "configuration_read_time"},
    {3, 150, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "CONFIG_DELAY_ENABLED", "IQData-Config-Delay-Enabled", "Configured delayed protection action", "configuration_read_time"},
    {3, 151, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "CONFIG_FOUR_WIRE", "IQData-Config-Four-Wire", "Configured four-wire AC system; false means three-wire", "configuration_read_time"},
    {3, 152, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "CONFIG_DEMAND_SYNC_ENABLED", "IQData-Config-Demand-Sync-Enabled", "External demand synchronization enabled; overrides internal demand window", "configuration_read_time"},
    {3, 153, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "CONFIG_PROTECTION_ENABLED", "IQData-Config-Protection-Enabled", "Internal protection functions enabled; external trip remains possible independently", "configuration_read_time"},
    {3, 154, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "CONFIG_TEST_MODE", "IQData-Config-Test-Mode", "Factory test switch is ON; readout only, never activates the test", "configuration_read_time"},
    {3, 155, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "CONFIG_ALTERNATE_PF", "IQData-Config-Alternate-PF", "Alternate power-factor calculation enabled by SW5 switch4 OFF", "configuration_read_time"},
    {3, 156, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "CONFIG_AUTO_RESET_ENABLED", "IQData-Config-Auto-Reset-Enabled", "Automatic reset attempts enabled; readout only", "configuration_read_time"},
    {3, 157, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "CONFIG_ENERGY_RESET_ENABLED", "IQData-Config-Energy-Reset-Enabled", "Front-panel energy reset enable switch; reading does not reset energy", "configuration_read_time"},
    {3, 158, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "CONFIG_OVERVOLTAGE_TRIP_ENABLED", "IQData-Config-Overvoltage-Trip-Enabled", "Configured overvoltage trip response; not relay state", "configuration_read_time"},
    {3, 159, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "CONFIG_OVERVOLTAGE_ALARM_ENABLED", "IQData-Config-Overvoltage-Alarm-Enabled", "Configured overvoltage alarm response; not relay state", "configuration_read_time"},
    {3, 160, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "CONFIG_UNDERVOLTAGE_TRIP_ENABLED", "IQData-Config-Undervoltage-Trip-Enabled", "Configured undervoltage trip response; not relay state", "configuration_read_time"},
    {3, 161, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "CONFIG_UNDERVOLTAGE_ALARM_ENABLED", "IQData-Config-Undervoltage-Alarm-Enabled", "Configured undervoltage alarm response; not relay state", "configuration_read_time"},
    {3, 162, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "CONFIG_PHASE_LOSS_REVERSAL_TRIP_ENABLED", "IQData-Config-Phase-Loss-Reversal-Trip-Enabled", "Configured phase loss/reversal trip response; not relay state", "configuration_read_time"},
    {3, 163, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "CONFIG_PHASE_LOSS_REVERSAL_ALARM_ENABLED", "IQData-Config-Phase-Loss-Reversal-Alarm-Enabled", "Configured phase loss/reversal alarm response; not relay state", "configuration_read_time"},
    {3, 164, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "CONFIG_PHASE_UNBALANCE_TRIP_ENABLED", "IQData-Config-Phase-Unbalance-Trip-Enabled", "Configured phase unbalance trip response; not relay state", "configuration_read_time"},
    {3, 165, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "CONFIG_PHASE_UNBALANCE_ALARM_ENABLED", "IQData-Config-Phase-Unbalance-Alarm-Enabled", "Configured phase unbalance alarm response; not relay state", "configuration_read_time"},
    {3, 166, 95, IQ_GROUP_SETTINGS, 1, 0, 3600.0, "CONFIG_PT_INTERNATIONAL", "IQData-Config-PT-International", "International 110 V PT secondary selection; overrides nominal voltage selection", "configuration_read_time"},
    {3, 200, 95, IQ_GROUP_DERIVED, 1, 0, 5.0, "LOW_PF_ACTIVE", "IQData-Low-PF-Active", "Absolute meter PF is below configured threshold", "gateway_session_reset_on_restart"},
    {3, 201, 95, IQ_GROUP_DERIVED, 1, 0, 5.0, "FREQUENCY_EXCURSION_ACTIVE", "IQData-Frequency-Excursion-Active", "Meter frequency is outside configured nominal frequency tolerance", "gateway_session_reset_on_restart"},
    {3, 202, 95, IQ_GROUP_DERIVED, 1, 0, 5.0, "VOLTAGE_EXCURSION_ACTIVE", "IQData-Voltage-Excursion-Active", "At least one line voltage is outside configured nominal voltage tolerance", "gateway_session_reset_on_restart"},
    {3, 203, 95, IQ_GROUP_DERIVED, 1, 0, 5.0, "ROLLING_DEMAND_READY", "IQData-Rolling-Demand-Ready", "A complete continuous 15-minute real-power window is available", "gateway_session_reset_on_restart"},
    {3, 204, 95, IQ_GROUP_DERIVED, 1, 0, 5.0, "ROLLING_HOUR_ENERGY_READY", "IQData-Rolling-Hour-Energy-Ready", "A complete continuous one-hour energy-counter window is available", "gateway_session_reset_on_restart"},
    {3, 205, 95, IQ_GROUP_DERIVED, 1, 0, 5.0, "ROLLING_DAY_ENERGY_READY", "IQData-Rolling-Day-Energy-Ready", "A complete continuous 24-hour energy-counter window is available", "gateway_session_reset_on_restart"},
};
