#!/usr/bin/env python3
"""Render portable user systemd units; install only with explicit --install.

This script never starts services, flashes firmware, installs dependencies, or
uses sudo. Review rendered units before installing and enabling them.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import datetime, timezone
import ipaddress
import os
from pathlib import Path
import re
import shutil
import sys
import tempfile


RUNTIME_FILES = ("poll_meter.py", "host.py", "bacnet_server.py", "db_snapshot.py")


def clean_text(value, label):
    value = str(value)
    if not value or any(ord(char) < 32 or ord(char) == 127 for char in value):
        raise ValueError(f"{label} must be nonempty and contain no control characters")
    return value


def absolute_path(value, label):
    resolved = Path(clean_text(value, label)).expanduser().resolve()
    clean_text(resolved, label)
    return resolved


def ipv4_endpoint(value, *, prefix):
    """Accept only a numeric IPv4 address, explicit UDP port, and optional mask."""
    pattern = r"([0-9.]+)/([0-9]{1,2}):([0-9]+)" if prefix else r"([0-9.]+):([0-9]+)"
    match = re.fullmatch(pattern, clean_text(value, "BACnet address"))
    if not match:
        example = "192.0.2.10/24:47808" if prefix else "192.0.2.20:47808"
        raise ValueError(f"Expected an IPv4 address in the form {example}")
    address = ipaddress.IPv4Address(match[1])
    if address.is_unspecified or address.is_multicast or address == ipaddress.IPv4Address("255.255.255.255"):
        raise ValueError("BACnet addresses must identify a host")
    port = int(match[3] if prefix else match[2])
    if not 1 <= port <= 65535:
        raise ValueError("BACnet UDP port must be between 1 and 65535")
    if prefix:
        network = ipaddress.IPv4Interface(f"{address}/{match[2]}")
        if network.network.prefixlen < 31 and address in (network.network.network_address, network.network.broadcast_address):
            raise ValueError("BACnet bind address must be a host, not the subnet/broadcast address")
        return f"{address}/{network.network.prefixlen}:{port}"
    return f"{address}:{port}"


def unit_word(value, *, command=False):
    """Quote one systemd word; prevent specifier and ExecStart env expansion."""
    value = clean_text(value, "Unit value")
    value = value.replace("\\", "\\\\").replace('"', '\\"').replace("%", "%%")
    if command:
        value = value.replace("$", "$$")
    return '"' + value + '"'


def command_line(*args):
    # systemd expands environment variables in arguments, never the executable.
    return " ".join(unit_word(arg, command=index > 0) for index, arg in enumerate(args))


def user_unit_dir():
    return absolute_path(Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "systemd/user", "User unit directory")


@dataclass(frozen=True)
class Config:
    root: Path
    data_dir: Path
    serial: str
    bacnet_address: str
    instance: int
    name: str
    metasys: str | None = None

    @classmethod
    def from_args(cls, args):
        root = absolute_path(args.root, "Repository path")
        data_dir = absolute_path(args.data_dir, "Data directory")
        if data_dir == root or root in data_dir.parents:
            raise ValueError("--data-dir must be outside the repository so state and databases stay out of Git")
        for filename in RUNTIME_FILES:
            if not (root / "live" / filename).is_file():
                raise ValueError(f"Missing runtime file: {root / 'live' / filename}")
        serial = clean_text(args.serial, "Serial path")
        serial_path = Path(serial)
        if serial_path.parent != Path("/dev/serial/by-id") or serial_path.name in (".", ".."):
            raise ValueError("--serial must be a persistent /dev/serial/by-id/DEVICE path")
        if not 0 <= args.instance <= 4194302:
            raise ValueError("--instance must be between 0 and 4194302 (4194303 is reserved)")
        name = clean_text(args.name, "BACnet name")
        if not name.strip():
            raise ValueError("--name must contain visible characters")
        return cls(root, data_dir, serial, ipv4_endpoint(args.bacnet_address, prefix=True),
                   args.instance, name, ipv4_endpoint(args.metasys, prefix=False) if args.metasys else None)


def render_units(config):
    live = config.root / "live"
    python = config.root / ".venv/bin/python"
    state = config.data_dir / "state"
    database = config.data_dir / "iqdata.sqlite"
    snapshot = config.data_dir / "iqdata-latest.sqlite"

    def service(description, argv, *, oneshot=False, poll=False):
        lines = ["# Generated by scripts/install_pi.py; regenerate after moving the repository.",
                 "[Unit]", f"Description={description}", "", "[Service]",
                 f"Type={'oneshot' if oneshot else 'simple'}",
                 # WorkingDirectory consumes the whole raw value, not a quoted
                 # argument list. Spaces/quotes/dollars are literal here.
                 "WorkingDirectory=" + str(live).replace("%", "%%"),
                 "ExecStart=" + command_line(python, "-u", *argv),
                 "UMask=0077", "NoNewPrivileges=true",
                 "StandardOutput=journal", "StandardError=journal"]
        if oneshot:
            lines.extend(["TimeoutStartSec=300", "Nice=10", "IOSchedulingClass=idle"])
        else:
            lines.extend(["Restart=on-failure", f"RestartSec={30 if poll else 5}", "TimeoutStopSec=10"])
            if poll:
                lines.extend(["KillSignal=SIGINT", "SuccessExitStatus=130"])
            lines.extend(["", "[Install]", "WantedBy=default.target"])
        return "\n".join(lines) + "\n"

    bacnet = [live / "bacnet_server.py", "--state", state, "--diagnostics", state / "bacnet-status.json",
              "--address", config.bacnet_address, "--instance", config.instance, "--name", config.name]
    if config.metasys:
        bacnet.extend(["--metasys", config.metasys])
    return {
        "iqdata-poll.service": service("IQ Data Plus II bounded USB polling", [
            live / "poll_meter.py", "--port", config.serial, "--state", state,
            "--kinds", "all_standard", "--duration-ms", 500, "--continuous", "--recover",
            "--interval", 1.05, "--database", database, "--diagnostics"], poll=True),
        "iqdata-http.service": service("IQ Data Plus II read-only LAN telemetry", [
            live / "host.py", "serve", "--bind", "0.0.0.0", "--port", 8080,
            "--state", state, "--database-snapshot", snapshot]),
        "iqdata-bacnet.service": service("IQ Data Plus II read-only BACnet/IP gateway", bacnet),
        "iqdata-snapshot.service": service("Consistent IQ Data Plus II database download", [
            live / "db_snapshot.py", database, snapshot], oneshot=True),
        "iqdata-snapshot.timer": """# Generated by scripts/install_pi.py.
[Unit]
Description=Refresh IQ Data Plus II download hourly

[Timer]
OnBootSec=2min
OnUnitInactiveSec=1h
AccuracySec=5s
Unit=iqdata-snapshot.service

[Install]
WantedBy=timers.target
""",
    }


def write_units(units, destination, *, replace=False):
    """Preflight all paths; back up every existing unit before replacements."""
    destination = absolute_path(destination, "Output directory")
    existing = [destination / name for name in units if (destination / name).exists() or (destination / name).is_symlink()]
    if any(path.is_symlink() or not path.is_file() for path in existing):
        raise ValueError("Refusing to replace symlink or non-file unit paths")
    if existing and not replace:
        raise ValueError("Unit files already exist; inspect them, then use --replace to back them up and replace them")
    destination.mkdir(parents=True, exist_ok=True)
    backup = None
    if existing:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        backup = Path(tempfile.mkdtemp(prefix=f"iqdata-backup-{stamp}-", dir=destination))
        for path in existing:
            shutil.copy2(path, backup / path.name)
    for name, content in units.items():
        # Atomic replacement avoids a half-written individual unit.
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=destination, delete=False) as file:
            temporary = Path(file.name)
            try:
                file.write(content)
                file.flush()
                os.fchmod(file.fileno(), 0o644)
            except BaseException:
                temporary.unlink(missing_ok=True)
                raise
        try:
            temporary.replace(destination / name)
        finally:
            temporary.unlink(missing_ok=True)
    return backup


def parser():
    result = argparse.ArgumentParser(description=__doc__)
    result.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1], help="Repository directory (default: this script's repository)")
    result.add_argument("--data-dir", type=Path, default=Path.home() / ".local/share/iqdata", help="Persistent state/database directory, outside the repository")
    result.add_argument("--serial", required=True, help="Persistent /dev/serial/by-id/DEVICE USB path")
    result.add_argument("--bacnet-address", required=True, help="Pi Ethernet IPv4/prefix:UDPport, e.g. 192.0.2.10/24:47808")
    result.add_argument("--instance", required=True, type=int, help="Unique BACnet device instance, e.g. 75151")
    result.add_argument("--name", required=True, help="BACnet device name")
    result.add_argument("--metasys", help="Optional directed I-Am destination, IPv4:UDPport")
    target = result.add_mutually_exclusive_group()
    target.add_argument("--output-dir", type=Path, help="Render only, to this directory (default: ROOT/build/systemd)")
    target.add_argument("--install", action="store_true", help="Install files for the current user; does not enable/start services")
    result.add_argument("--replace", action="store_true", help="Back up and replace existing unit files")
    return result


def main(argv=None):
    cli = parser()
    args = cli.parse_args(argv)
    try:
        config = Config.from_args(args)
        units = render_units(config)
        installed_dir = user_unit_dir()
        destination = installed_dir if args.install else absolute_path(args.output_dir or config.root / "build/systemd", "Output directory")
        if not args.install and (destination == installed_dir or installed_dir in destination.parents):
            raise ValueError("Rendering to the active user unit directory requires --install")
        if args.install:
            if not sys.platform.startswith("linux"):
                raise ValueError("--install is supported only on Linux with user systemd; render with --output-dir here")
            python = config.root / ".venv/bin/python"
            if not python.is_file() or not os.access(python, os.X_OK):
                raise ValueError(f"Create the Python virtual environment first: {python}")
        backup = write_units(units, destination, replace=args.replace)
        if args.install:
            (config.data_dir / "state").mkdir(parents=True, exist_ok=True, mode=0o700)
        print(f"{'Installed' if args.install else 'Rendered'} {len(units)} units in {destination}")
        if backup:
            print(f"Previous unit files backed up in {backup}")
        if args.install:
            print("Services have not been started. Next: systemctl --user daemon-reload")
        else:
            print("No active services, data directories, or user unit files were changed. Review these units, then repeat with --install.")
        return 0
    except (OSError, ValueError) as error:
        cli.exit(2, f"Setup failed: {error}\n")


if __name__ == "__main__":
    raise SystemExit(main())
