#!/usr/bin/env python3
"""Generate the immutable P4 catalog directly from the published Pi CSV."""
import argparse
import csv
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[3]
PORT = ROOT / 'firmware/esp32-p4'


def generate():
    source = ROOT / 'live/BACNET_POINT_MAP.csv'
    rows = [r for r in csv.DictReader(source.open()) if r['is_point'] == 'true']
    assert len(rows) == 198
    assert sum(r['object_type_code'] == '0' for r in rows) == 106
    assert sum(r['object_type_code'] == '3' for r in rows) == 92
    assert len({(r['object_type_code'], r['object_instance']) for r in rows}) == 198
    assert len({r['object_name'] for r in rows}) == 198
    assert len({r['source_key'] for r in rows}) == 198
    groups = ['live', 'live_health', 'flags', 'settings', 'trip', 'derived', 'health']
    header = ['/* Generated by tools/generate_points.py; do not edit. */',
              '#pragma once', '#include <stdint.h>', '#include <stddef.h>',
              'enum { IQ_POINT_COUNT = 198 };',
              'typedef enum { ' + ', '.join('IQ_GROUP_' + g.upper() for g in groups) + ' } iq_group_t;',
              'typedef enum {']
    body = ['/* Generated; CSV SHA256: ' + hashlib.sha256(source.read_bytes()).hexdigest() + ' */',
            '#include "iq_points.h"', 'const iq_point_def_t iq_points[IQ_POINT_COUNT] = {']
    for n, r in enumerate(rows):
        key = re.sub(r'[^A-Za-z0-9_]', '_', r['source_key'])
        header.append(f'    IQ_{key} = {n},')
        strings = ', '.join(json.dumps(r[k]) for k in ('source_key', 'object_name', 'description', 'time_context'))
        body.append('    {%s, %s, %s, IQ_GROUP_%s, %s, %s, %s, %s},' % (
            r['object_type_code'], r['object_instance'], r['units_code'], r['group'].upper(),
            r['scale'], r['cov_increment'] or '0', r['max_age_seconds'] or '0', strings))
    header += ['} iq_key_t;',
               'typedef struct {',
               '    uint16_t object_type, instance, units;',
               '    iq_group_t group;',
               '    double scale, cov_increment, max_age;',
               '    const char *key, *name, *description, *time_context;',
               '} iq_point_def_t;',
               'extern const iq_point_def_t iq_points[IQ_POINT_COUNT];', '']
    body += ['};', '']
    return {'iq_points.h': '\n'.join(header), 'iq_points.c': '\n'.join(body)}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, text in generate().items():
        path = PORT / 'main' / name
        if args.check:
            assert path.read_text() == text, f'{path} differs from published CSV'
        else:
            path.write_text(text)
    print('198 points: 106 AI, 92 BI; metadata matches published CSV')
